Polls/urls.py
from django.urls import path

from . import views

app_name = 'Polls'
urlpatterns = [
    path('', views.index.as_view(), name='index'),
    # path('<int:question_id>/', views.detail, name='detail'),
    path('<int:pk>/', views.detail.as_view(), name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('create', views.create_item, name='create_item'),
    path('update/<int:question_id>/', views.update_item, name='update_item'),
    path('delete/<int:question_id>/', views.delete_item, name='delete_item'),
]

Treinando/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('Polls.urls')),
    path('admin/', admin.site.urls),
]

Polls/models.py
import datetime

from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published',
                                    null=True,
                                    blank=True,
                                    )
    pub_date.input_formats = ['%Y-%m-%d',
                              '%m/%d/%Y',
                              '%m/%d/%y']

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

Polls/forms.py
import self as self
from django import forms
from .models import Question, Choice


class ItemForm(forms.ModelForm):
    question_text = forms.CharField(max_length=200)

    class Meta:
        model = Question
        fields = ('question_text',)


    #
    #      <form>
    #       <div class="form-group">
    #         <label for="exampleInputEmail1">Question text</label>
    # <!--        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter question text">-->
    # <!--        {{ form.question_text }}-->
    #           {% render_field form.question_text type="text" %}
    #       </div>
    #
    #       <div class="form-group">
    #         <label for="exampleInputPassword1">Date of publication</label>
    # <!--        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Pub. Date">-->
    #           {% render_field form.pub_date type="date" %}
    #       </div>
    #
    #       <!-- <div class="form-check">
    #         <input type="checkbox" class="form-check-input" id="exampleCheck1">
    #         <label class="form-check-label" for="exampleCheck1">Check me out</label>
    #       </div> -->
    #
    #       <button type="submit" class="btn btn-primary">Submit</button>

Polls/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Question, Choice
from .forms import ItemForm


# Create your views here.
class index(generic.ListView):
    template_name = 'Polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')

class detail(generic.DetailView):
    model = Question
    template_name = 'Polls/detail.html'

    # How to pass aditional context data

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['var'] = Choice.objects.filter(pk=pk)


 ###################### Regular views ###################


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {
#         'latest_question_list': latest_question_list
#     }
#     return render(request, 'polls/index.html', context)
#     # return HttpResponse("Pooooooooooooooooooooolls")

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     choices = question.choice_set.all()
#     context = {
#         'question': question,
#         'choices': choices,
#     }
#     return render(request, 'polls/detail.html', context)
#     # return HttpResponse("You are looking at question %s." % question_id)


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'Polls/detail.html', {'question': question, 'error_message': "You didn't select a choice or you tried to vote when there's none.",})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
    return HttpResponseRedirect(reverse('Polls:results', args=(question.id,)))


def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('Polls:index')

    # context = {'form': form }
    return render(request, 'polls/item-form.html', {'form': form })
    # return HttpResponse("Not made yet.")

def update_item(request, question_id):
    question = Question.objects.get(id=question_id)
    form = ItemForm(request.POST or None, instance=question)

    if form.is_valid():
        form.save()
        return redirect('Polls:index')

    context = {'form': form, 'question': question}
    return render(request, 'Polls/item-form.html', context)

def delete_item(request, question_id):
    question = Question.objects.get(id=question_id)

    if request.method == 'POST':
        question.delete()
        return redirect('food:index')

    return render(request, 'Polls/item-delete.html', {'question': question})

Polls/templates/includes/configuration-plugin.html
        <div class="custom-template">
			<div class="title">Settings</div>
			<div class="custom-content">
				<div class="switcher">
					<div class="switch-block">
						<h4>Logo Header</h4>
						<div class="btnSwitch">
							<button type="button" class="changeLogoHeaderColor" data-color="dark"></button>
							<button type="button" class="selected changeLogoHeaderColor" data-color="blue"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="purple"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="light-blue"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="green"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="orange"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="red"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="white"></button>
							<br/>
							<button type="button" class="changeLogoHeaderColor" data-color="dark2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="blue2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="purple2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="light-blue2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="green2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="orange2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="red2"></button>
						</div>
					</div>
					<div class="switch-block">
						<h4>Navbar Header</h4>
						<div class="btnSwitch">
							<button type="button" class="changeTopBarColor" data-color="dark"></button>
							<button type="button" class="changeTopBarColor" data-color="blue"></button>
							<button type="button" class="changeTopBarColor" data-color="purple"></button>
							<button type="button" class="changeTopBarColor" data-color="light-blue"></button>
							<button type="button" class="changeTopBarColor" data-color="green"></button>
							<button type="button" class="changeTopBarColor" data-color="orange"></button>
							<button type="button" class="changeTopBarColor" data-color="red"></button>
							<button type="button" class="changeTopBarColor" data-color="white"></button>
							<br/>
							<button type="button" class="changeTopBarColor" data-color="dark2"></button>
							<button type="button" class="selected changeTopBarColor" data-color="blue2"></button>
							<button type="button" class="changeTopBarColor" data-color="purple2"></button>
							<button type="button" class="changeTopBarColor" data-color="light-blue2"></button>
							<button type="button" class="changeTopBarColor" data-color="green2"></button>
							<button type="button" class="changeTopBarColor" data-color="orange2"></button>
							<button type="button" class="changeTopBarColor" data-color="red2"></button>
						</div>
					</div>
					<div class="switch-block">
						<h4>Sidebar</h4>
						<div class="btnSwitch">
							<button type="button" class="selected changeSideBarColor" data-color="white"></button>
							<button type="button" class="changeSideBarColor" data-color="dark"></button>
							<button type="button" class="changeSideBarColor" data-color="dark2"></button>
						</div>
					</div>
					<div class="switch-block">
						<h4>Background</h4>
						<div class="btnSwitch">
							<button type="button" class="changeBackgroundColor" data-color="bg2"></button>
							<button type="button" class="changeBackgroundColor selected" data-color="bg1"></button>
							<button type="button" class="changeBackgroundColor" data-color="bg3"></button>
							<button type="button" class="changeBackgroundColor" data-color="dark"></button>
						</div>
					</div>
				</div>
			</div>
			<div class="custom-toggle">
				<i class="flaticon-settings"></i>
			</div>
		</div>

        

Polls/templates/includes/footer.html
			<footer class="footer">
				<div class="container-fluid">
					<nav class="pull-left">
						<ul class="nav">
							<li class="nav-item">
                                <a class="nav-link" 
                                   target="_blank" 
                                   href="{% url 'core:home' %}">
									Captura NFe
								</a>
							</li>
						</ul>
					</nav>
					<div class="copyright ml-auto">
                        &copy; <a target="_blank" href="https://integrati.solutions/">Sistema de Captura de Notas Fiscais</a>
                        - Powerad by <a target="_blank" href="#">IntegraTI</a>
					</div>				
				</div>
            </footer>
            

Polls/templates/includes/navigation.html
<div class="main-header">

    <!-- Logo Header -->
    <div class="logo-header" data-background-color="dark2">

        <a href="{% url 'core:home' %}" class="logo">
            <img src="/static/assets/img/logo.png" alt="navbar brand" class="navbar-brand">
        </a>
        <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse"
                data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon">
						<i class="icon-menu"></i>
					</span>
        </button>
        <button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
        <div class="nav-toggle">
            <button class="btn btn-toggle toggle-sidebar">
                <i class="icon-menu"></i>
            </button>
        </div>
    </div>
    <!-- End Logo Header -->

    <!-- Navbar Header -->
    <nav class="navbar navbar-header navbar-expand-lg" data-background-color="dark">

        {% if request.user.is_authenticated %}
            <div class="container-fluid">
                <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
                    <li class="nav-item toggle-nav-search hidden-caret">
                        <a class="nav-link" data-toggle="collapse" href="#search-nav" role="button"
                           aria-expanded="false" aria-controls="search-nav">
                            <i class="fa fa-search"></i>
                        </a>
                    </li>

                    <li class="nav-item dropdown hidden-caret">
                        <div class="dropdown-menu quick-actions quick-actions-info animated fadeIn">
                            <div class="quick-actions-header">
                                <span class="title mb-1">Quick Actions</span>
                                <span class="subtitle op-8">Shortcuts</span>
                            </div>
                            <div class="quick-actions-scroll scrollbar-outer">
                                <div class="quick-actions-items">
                                    <div class="row m-0">
                                        <a class="col-6 col-md-4 p-0" href="#">
                                            <div class="quick-actions-item">
                                                <i class="flaticon-file-1"></i>
                                                <span class="text">Generated Report</span>
                                            </div>
                                        </a>
                                        <a class="col-6 col-md-4 p-0" href="#">
                                            <div class="quick-actions-item">
                                                <i class="flaticon-database"></i>
                                                <span class="text">Create New Database</span>
                                            </div>
                                        </a>
                                        <a class="col-6 col-md-4 p-0" href="#">
                                            <div class="quick-actions-item">
                                                <i class="flaticon-pen"></i>
                                                <span class="text">Create New Post</span>
                                            </div>
                                        </a>
                                        <a class="col-6 col-md-4 p-0" href="#">
                                            <div class="quick-actions-item">
                                                <i class="flaticon-interface-1"></i>
                                                <span class="text">Create New Task</span>
                                            </div>
                                        </a>
                                        <a class="col-6 col-md-4 p-0" href="#">
                                            <div class="quick-actions-item">
                                                <i class="flaticon-list"></i>
                                                <span class="text">Completed Tasks</span>
                                            </div>
                                        </a>
                                        <a class="col-6 col-md-4 p-0" href="#">
                                            <div class="quick-actions-item">
                                                <i class="flaticon-file"></i>
                                                <span class="text">Create New Invoice</span>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="nav-item dropdown hidden-caret">
                        <div class="nav-clock">
                        <div class="time">
                            <span class="time-hours"></span>
                            <span class="time-min"></span>
                            <span class="time-sec"></span>
                        </div>
                    </div><!-- nav-clock -->
{#                        <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">#}
{#                            <div class="avatar-sm">#}
{#                                <span class="avatar-title rounded-circle border border-white bg-dark tx-white"><i class="typcn typcn-pi-outline"></i> </span>#}
{#                            </div>#}
{#                        </a>#}
{#                        <ul class="dropdown-menu dropdown-user animated fadeIn">#}
{#                            <div class="dropdown-user-scroll scrollbar-outer">#}
{#                                <li>#}
{#                                    <div class="user-box">#}
{#                                        <div class="avatar-lg"><img src="/static/assets/img/profile.jpg"#}
{#                                                                    alt="image profile" class="avatar-img rounded">#}
{#                                        </div>#}
{#                                        <div class="u-text">#}
{#                                            <h4>#}
{#                                                {{ request.user.username }}#}
{#                                            </h4>#}
{#                                            <p class="text-muted">#}
{#                                                {{ request.user.email }}#}
{#                                            </p>#}
{#                                            <a href="#" class="btn btn-xs btn-secondary btn-sm">Perfil</a>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </li>#}
{#                                <li>#}
{#                                    <div class="dropdown-divider"></div>#}
{#                                    <a class="dropdown-item" href="#">Meu Perfil</a>#}
{#                                    <div class="dropdown-divider"></div>#}
{#                                    <a class="dropdown-item" href="#">Configurações</a>#}
{#                                    <div class="dropdown-divider"></div>#}
{#                                    <a class="dropdown-item" href="{% url 'logout' %}">Sair do sistema</a>#}
{#                                </li>#}
{#                            </div>#}
{#                        </ul>#}
                    </li>
                </ul>
            </div>
        {% endif %}

    </nav>
    <!-- End Navbar -->
</div>
        

Polls/templates/includes/scripts.html
	<!--   Core JS Files   -->
	<script src="/static/assets/js/core/jquery.3.2.1.min.js"></script>
    <script src="/static/assets/plugins/jquery-ui-1.12.1/jquery-ui.min.js"></script>#
	<script src="/static/assets/js/core/popper.min.js"></script>
	<script src="/static/assets/js/core/bootstrap.min.js"></script>

	<!-- jQuery UI -->
	<script src="/static/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
	<script src="/static/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>

	<!-- jQuery Scrollbar -->
	<script src="/static/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>

	<!-- Chart JS -->
	<script src="/static/assets/js/plugin/chart.js/chart.min.js"></script>

	<!-- jQuery Sparkline -->
	<script src="/static/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>

	<!-- Chart Circle -->
	<script src="/static/assets/js/plugin/chart-circle/circles.min.js"></script>

	<!-- Datatables -->
    <script src="/static/assets/plugins/datatables/dataTables.min.js"></script>
	<script src="/static/assets/plugins/datatables/dataTables.bootstrap4.min.js"></script>
	<script src="/static/assets/plugins/datatables/dataTables.responsive.min.js"></script>
	<script src="/static/assets/plugins/datatables/dataTables.buttons.min.js"></script>
    <!-- Select 2 -->
    <script src="/static/assets/plugins/select2/dist/js/select2.min.js"></script>
    <!-- DataTPiker -->
    <script src="/static/assets/plugins/daterangepicker/daterangepicker.js"></script>


{#	<script src="/static/assets/js/plugin/datatables/buttons.bootstrap4.min.js"></script>#}
{#	<script src="/static/assets/js/plugin/datatables/jszip.min.js"></script>#}
{#	<script src="/static/assets/js/plugin/datatables/buttons.html5.min.js"></script>#}
{#	<script src="/static/assets/js/plugin/datatables/buttons.print.min.js"></script>#}



	<!-- Bootstrap Notify -->
	<script src="/static/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>


	<!-- jQuery Vector Maps -->
	<script src="/static/assets/js/plugin/jqvmap/jquery.vmap.min.js"></script>
	<script src="/static/assets/js/plugin/jqvmap/maps/jquery.vmap.world.js"></script>

	<!-- Sweet Alert -->
	<script src="/static/assets/js/plugin/sweetalert/sweetalert.min.js"></script>


	<!-- Atlantis JS -->
    <script src="/static/assets/js/atlantis.min.js"></script>

Polls/templates/includes/sidebar.html
<!-- Sidebar -->
<div class="sidebar sidebar-style-2" data-background-color="dark2">
    <div class="sidebar-wrapper scrollbar scrollbar-inner nav-collapse">
        <div class="sidebar-content">
            {% if request.user.is_authenticated %}
                <div class="user">
                    <div class="avatar-sm float-left mr-2">
                            <span class="avatar-title rounded-circle border border-white bg-primary tx-color-01 bold">
                                {{ request.user.username|slice:1|upper }}
                           </span>
                    </div>
                    <div class="info">
                        <a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
								<span>
									{{ request.user.username }}
									<span class="user-level">
										{{ request.user.email }}
									</span>
									<span class="caret"></span>
								</span>
                        </a>
                        <div class="clearfix"></div>

                        <div class="collapse in" id="collapseExample">
                            <ul class="nav">
                                <li>
                                    <a href="#profile">
                                        <span class="link-collapse">Meu Perfil</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'logout' %}">
                                        <span class="link-collapse">Sair do Sistema</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <ul class="nav nav-primary">
                    <li class="nav-item {% if 'index' in segment %} active {% endif %}">
                        <a href="#dashboard"
                           data-toggle="collapse"
                           class="collapse-toggle"
                           aria-expanded="false">
                            <i class="fas fa-home"></i>
                            <p>Dashboard</p>
                            <span class="caret"></span>
                        </a>
                        <div class="collapse" id="dashboard">
                            <ul class="nav nav-collapse">
                                <li>
                                    <a href="{% url 'core:home' %}">
                                        <span class="sub-item">Dashboard</span>
                                    </a>
                                </li>
{#                                <li>#}
{#                                    <a href="{% url 'core:dasboard_resumo' %}">#}
{#                                        <span class="sub-item">Resumo de Notas</span>#}
{#                                    </a>#}
{#                                </li>#}
                            </ul>
                            <ul class="nav nav-collapse">

                            </ul>
                        </div>
                    </li>
                    <li class="nav-section">
							<span class="sidebar-mini-icon">
								<i class="fa fa-ellipsis-h"></i>
							</span>
                        <h4 class="text-section">Administração</h4>
                    </li>
                    <li class="nav-item {% if 'widgets' in segment %} active {% endif %}">
                        <a href="/admin">
                            <i class="fas fa-desktop"></i>
                            <p>Configurações</p>
                            {#								<span class="badge badge-success"></span>#}
                        </a>
                    </li>
                </ul>
            {% endif %}
        </div>
    </div>
</div>
<!-- End Sidebar -->
        

Polls/templates/polls/base.html
{% load bootstrap4 %}
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Polls baby - {% block titulo %} {% endblock %} </title>
<!--    <link rel="stylesheet" href="{#  static 'polls/style.css' #}">-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</head>
<body>
    {% csrf_token %}
    {% block boostrap4_content %}
    <nav class="p-2 navbar navbar-dark bg-primary text-dark">
        <a href="{% url 'Polls:index' %}" class="navbar-brand text-white">PollsApp</a>

        <div class="navbar">
            <a class="nav-item nav-link text-white" href="{% url 'Polls:create_item' %}">Add Poll</a>
            <a class="nav-item nav-link text-white" href="#">Delete Poll</a>
            <a class="nav-item nav-link text-white" href="#">View Poll</a>
        </div>
    </nav>

    <nav class="p2 w-100 navbar" style="background-color: #000000"> </nav>

     <div class="container">

        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}
        {% endblock %}

    </div>

    {% if form.errors %}
        <div class="col-lg-12">
        <div class="alert alert-outline alert-success alert-dismissible fade show d-flex align-items-center"
             role="alert" id="message">
            <i data-feather="alert-circle" class="mg-r-10"></i> {{ form.errors }}
        </div>
       </div>
    {% endif %}
    {% if messages %}
    <div class="col-lg-12">
        <div class="alert alert-outline alert-success alert-dismissible fade show d-flex align-items-center"
             role="alert" id="message">
            {% for message in messages %}
                <i data-feather="alert-circle" class="mg-r-10"></i> {{ message }}
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&bigotimes;</span>
            </button>
        </div>
    </div>
    {% endif %}

    {% endblock %}



    {% block body %}
    {% endblock %}


</body>
</html>

Polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block titulo %}Detail{% endblock %}
</head>
<body>

    {% block body %}

    <form action="{% url 'Polls:vote' question.id %}" method="post">
    {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if question.choice_set.all %}
                {% for choice in question.choice_set.all %}
                <li>
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    {{ choice.choice_text }}
                </li>
                {% endfor %}
            {% else %}
                <p>No choices are available.</p>
                {% if error_message %}
                    <p>{{ error_message }}</p>
                {% endif %}
            {% endif %}
        </fieldset>
        <input type="submit" class="btn btn-light" value="Vote">
    </form>
    <a href="{% url 'Polls:delete_item' question.id %}" class="btn btn-danger">Delete</a>
    {% endblock %}

</body>
</html>

Polls/templates/polls/index.html
{% extends 'polls/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width", initial-scale="1.0">
    {% block titulo %}Principal{% endblock %}
</head>
<body>

    {% block body %}

    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li>
                <div class="text-right mb-3">
                    <a href="{% url 'Polls:detail' question.id %}" class="col-4">Pergunta: {{ question.question_text }}</a>
                    <a href="{% url 'Polls:update_item' question.id %}" type="button" class="btn btn-info btn-sm">Edit</a>
                </div>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

    {% endblock %}

</body>
</html>

Polls/templates/polls/item-delete.html
{% extends 'polls/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block titulo %}Delete poll{% endblock %}
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

Polls/templates/polls/item-form.html
{% extends 'polls/base.html' %}
{% load widget_tweaks %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block titulo %}Add new{% endblock %}
</head>
<body>

    {% block body %}


    <!-- <form method="POST">
        {# csrf_token #}
        {# form #}
        <button type = "submit" class="btn btn-primary">Save</button>
    </form> -->

    <form method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button type="submit" class="btn btn-primary">Save</button>
        {% endbuttons %}

    </form>

    <!-- if form.errors estava aqui -->

    {% endblock %}

</body>
</html>

Polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}Results{% endblock %}
</head>
<body>
    {% block body %}

<!--    <legend>-->
    <h1>{{ question.question_text }}</h1>
<!--    </legend>-->

    <ul>
        {% for choice in question.choice_set.all %}
            <li>
                {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
            </li>
        {% endfor %}
    </ul>

    <a href="{% url 'Polls:detail' question.id %}">Vote again?</a>

    {% endblock %}
</body>
</html>